### ISSUE TITLE
Issue with Lower case Alias names

### ISSUE THREAD

**Issue by smur89** [playframework/anorm#96] opened 2016-04-15 14:49 UTC
I see you guys are going to release v2.5.1, and I wanted to check that this version would work for us and allow us to upgrade. (See https://github.com/playframework/anorm/issues/94) Good news is it works fine with our current implementation, but if we change our alias' back to lower case run into an issue.

We changed to upper case due to this:
http://stackoverflow.com/a/36551747/1413470

Seems like the solution for this would be to set a to uppercase here:
https://github.com/playframework/anorm/blob/master/core/src/main/scala/anorm/Row.scala#L127
as all the column names in the metaData are uppercase.

```
An exception or error caused a run to abort: ColumnName(test_users.test_users_email,Some(user_email)) 
anorm.AnormException: ColumnName(test_users.test_users_email,Some(user_email))
```

**Comment by cchantep** [comment] 2016-04-15 16:20
Hi,

As said on the ticket #94, the issue is fixed on master.
Release are done from master.

> P.S. Please use the [MailingList](https://groups.google.com/forum/#!forum/play-framework) to ask question. This tracker is for confirmed issue/actionable feature.

Best regards.

**Closed by cchantep** 2016-04-15 16:20 UTC

**Comment by smur89** [comment] 2016-04-15 16:22
Hi @cchantep I encountered this issue on master. It is separate from #94.

Will use the MailingList in future. Thanks

**Comment by cchantep** [comment] 2016-04-15 19:55
The case of the meta is choosen by the driver. If it exposes all in upper case ...
